name: greeter

on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  greet-new-user:
    runs-on: ubuntu-latest
    steps:
      - name: First interaction
        uses: anishanne/greeter@V1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: "![](https://cdn.anishdoes.dev/githublight.png)\nHey @{user}! Welcome to the **Greeter** repo on **Github**."
