name: CI

on:
  push:
    branches:
    - main
jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        run: |
          echo "$HOME/.bin" >> $GITHUB_PATH
          curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh > /tmp/tfswitch-install.sh
          chmod +x /tmp/tfswitch-install.sh
          /tmp/tfswitch-install.sh -b $HOME/.bin
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: get terraform
        run: tfswitch -b $HOME/.bin/terraform
      -
        name: terraform init 
        run: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && echo "$m - init" && terraform init -input=false -backend=true) || exit 1; done
      -
        name: terraform validate
        run: find . -name ".terraform" -prune -o -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && echo "$m - validate" && terraform validate && echo "√ $m") || exit 1 ; done
      -
        name: terraform ibm check 
        run: terraform plan -var="commit=${{ env.GITHUB_ACTION }}" -var="TF_VAR_AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="TF_VAR_AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="ibmcloud_api_key=${{ secrets.IBMCLOUD_API_KEY }}" -var="region=jp-tok" -var="resource_group=CDE" -var=ssh_key="hyperion-jp-tok" -out default.tfplan

      - name: First interaction
        uses: actions/first-interaction@v1.1.0
        with:
          # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Comment to post on an individual's first issue
          issue-message: "Thanks for opening an issue! This message was triggered by a Github Action"
          # Comment to post on an individual's first pull request
          pr-message: # optional

